server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yeb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    # spring自带的连接池
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回后自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认180000（30分钟）
      max-lifetime: 180000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# mybatis-plus
mybatis-plus:
  # 配置mapper映射文件位置
  mapper-locations: classpath*:/mapper/*.xml
  # 配置实体类别名
  type-aliases-package: com.wuyiz.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

## mybatis sql 打印（mapper方法接口所在的包，不是mapper.xml）
logging:
  level:
    com.wuyiz.server.mapper: debug

# JWT令牌服务属性
jwt:
  # jwt存储的请求头
  tokenHeader: Authorization
  # jwt加解密使用的密钥
  secret: yeb-secret
  # jwt的过期时间（60*60*24）
  expiration: 604800
  # jwt负载中拿到开头
  tokenHead: Bearer

